apiVersion: v1
kind: Service

metadata:
  name: demo-api-v1
  namespace: playground

  labels:
    app: demo-api
    env: dev
    version: v1

spec:
  type: ClusterIP
  selector:
    app: demo-api
    env: dev
    version: v1

  ports:
    - name: web
      protocol: TCP
      port: 80
      targetPort: web

---
## Ingress
# -----------------------------------------------------------------------------
#apiVersion: networking.k8s.io/v1
#kind: Ingress
#metadata:
#  name: demo-api
#  labels:
#    app: demo-api
#    env: dev
#  annotations:
#    kubernetes.io/ingress.class: "nginx"
#    nginx.ingress.kubernetes.io/affinity: "cookie"
#    nginx.ingress.kubernetes.io/session-cookie-name: "autoincrement"
#spec:
#  rules:
#    - host: "playground.dev.flow.com"
#      http:
#        paths:
#          - pathType: ImplementationSpecific
#            path: /
#            backend:
#              service:
#                name: demo-api-v1
#                port:
#                  number: 80