apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  env: dev
resources:
- deployment.yml
- ingress.yml

images:
- name: gcr.io/playground-369107/static-site
  newName: gcr.io/playground-369107/static-site
