## Deployment
# -----------------------------------------------------------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  # This is the full name of your deployment. It must be unique
  name: flow-playground-api-v1

  # Best practice labels:
  #   app: <app-name> (the non-unique version of metadata.name)
  #   kind: [web|worker]
  #   env: [staging|production|canary|test|dev]
  #   owner: who to ask about this service
  #   version: the major version of this service (v1//v1beta1)
  labels:
    app: flow-playground-api
    kind: web
    env: staging
    owner: Kan
    version: v1

spec:
  replicas: 1
  selector:
    matchLabels:
      app: flow-playground-api
      env: staging
      version: v1

  # Deployment strategy dictates how an update will be rolled out across the deployment
  # K8s will try to roll up to the maxSurge before taking pods offline
  # If availability is a strong concern, increase surge and decrease unavailable
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%

  template:
    metadata:
      annotations:
        # Set to "false" to opt out of prometheus scrapes
        # Prometheus still needs a port called "metrics" (below) to scrape properly
        prometheus.io/scrape: "true"

        ###
        #  TODO
        #
        #. NOTE!  This deployment isn't ready to serve metrics yet, and will require
        #         an nginx Prometheus exporter.
        ###

        # Set the path to the API endpoint that exposes prometheus metrics, or leave blank for `/metrics`
        prometheus.io/path: "/metrics"

      labels:
        app: flow-playground-api
        env: staging
        owner: Kan
        version: v1
        kind: web

    spec:
      serviceAccountName: flow-playground-cloud
      # Affinity keeps your replicas from all being scheduled to
      # nodes in the same zone. Prevents zonal failures from taking
      # down your entire service
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              podAffinityTerm:
                topologyKey: failure-domain.beta.kubernetes.io/zone
                labelSelector:
                  matchLabels:
                    app: flow-playground-api
                    env: staging
                    version: v1
      containers:
        - name: cloudsql-proxy
          image: gcr.io/cloudsql-docker/gce-proxy:1.32.0
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 200m
              memory: 128Mi
          command:
            [
              "/cloud_sql_proxy",
              "-instances=dl-flow-devex-staging:us-west1:key-indexing-staging-database-e5dff5ff=tcp:5432",
            ]

        - name: flow-playground-api
          image: us-west1-docker.pkg.dev/dl-flow-devex-staging/backend/playground-api:placeholder
          imagePullPolicy: Always

          # Ports exposed can be named so other resources can reference
          # them by name and not have to hard code numbers
          ports:
            - name: web
              containerPort: 8080

          env:
            - name: FLOW_PLATFORM_PLATFORMTYPE
              value: "STAGING"
            - name: FLOW_FORCEMIGRATION
              value: "false"
            - name: FLOW_ALLOWEDORIGINS
              value: "https://play.staging.onflow.org"
            - name: FLOW_PLAYGROUNDBASEURL
              value: "https://play.staging.onflow.org"
            - name: FLOW_DEBUG
              value: "true"
            - name: FLOW_STORAGEBACKEND
              value: "postgresql"
            - name: FLOW_SESSIONCOOKIESSAMESITENONE
              value: "true"
            - name: TELEMETRY_TRACINGENABLED
              value: "false"
            - name: TELEMETRY_TRACINGCOLLECTORENDPOINT
              value: "grafana-tracing-agent.sre.svc.cluster.local:4317"
            - name: FLOW_DB_HOST
              value: "127.0.0.1"
            - name: FLOW_DB_PORT
              value: "5432"
            - name: FLOW_DB_NAME
              value: "flow-playground-db"
            - name: FLOW_DB_USER
              value: "flow-playground"
            - name: FLOW_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: flow-playground-credentials
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: APP_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['app']
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: project=flow-devex,app=$(APP_NAME),pod=$(POD_NAME)

          # Readiness and Liveness probes
          readinessProbe:
            initialDelaySeconds: 1
            periodSeconds: 10
            httpGet:
              path: /ping
              port: web

          # Resource requests and constraints
          resources:
            requests:
              cpu: "200m" # 0.1 CPUs, or 10% CPU
              memory: "512Mi"
            limits:
              cpu: "800m"
              memory: "1024Mi"
      nodeSelector:
        ops.dapperlabs.com/preferred-namespace: backend