apiVersion: v1
kind: Service

metadata:
  name: flow-playground-api-v1
  namespace: backend

  labels:
    app: flow-playground-api
    env: staging
    version: v1

spec:
  type: ClusterIP
  selector:
    app: flow-playground-api
    env: staging
    version: v1

  ports:
    - name: web
      protocol: TCP
      port: 8080
      targetPort: web # reference to the name of the port in your container config

---
## Ingress
# -----------------------------------------------------------------------------
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flow-playground-api
  labels:
    app: flow-playground-api
    env: staging
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/session-cookie-name: "autoincrement"
spec:
  rules:
    - host: "playground.staging.flow.com"
      http:
        paths:
          - pathType: ImplementationSpecific
            path: /
            backend:
              service:
                name: flow-playground-api-v1
                port:
                  number: 8080